// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

public interface StudentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Students)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Student students = 1;</code>
   */
  java.util.List<proto.example.Schema.Student> 
      getStudentsList();
  /**
   * <code>repeated .Student students = 1;</code>
   */
  proto.example.Schema.Student getStudents(int index);
  /**
   * <code>repeated .Student students = 1;</code>
   */
  int getStudentsCount();
  /**
   * <code>repeated .Student students = 1;</code>
   */
  java.util.List<? extends proto.example.Schema.StudentOrBuilder> 
      getStudentsOrBuilderList();
  /**
   * <code>repeated .Student students = 1;</code>
   */
  proto.example.Schema.StudentOrBuilder getStudentsOrBuilder(
      int index);
}
