// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 uid = 2;</code>
   */
  int getUid();

  /**
   * <code>string department = 3;</code>
   */
  java.lang.String getDepartment();
  /**
   * <code>string department = 3;</code>
   */
  com.google.protobuf.ByteString
      getDepartmentBytes();
}
